"""CapabilityManifest — builds and caches the workflow_manifest.txt file."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from anythink.workflow.models import StageType

if TYPE_CHECKING:
    from anythink.config.models import ModelRegistry
    from anythink.mcp.manager import MCPManager
    from anythink.workflow.registry import WorkflowCapabilityRegistry
    from anythink.workflow.storage import WorkflowStorage

# Providers that run locally (no cloud API key required)
_LOCAL_PROVIDERS: frozenset[str] = frozenset(
    ["ollama", "lm_studio", "llamacpp", "lmstudio", "localai"]
)

# MCP tool name fragments that mark an operation as destructive
_DESTRUCTIVE_TOOL_FRAGMENTS: frozenset[str] = frozenset(
    [
        "write_file", "delete_file", "delete_folder", "move_file",
        "rename_file", "copy_file", "send_email", "delete_email",
        "move_email", "create_event", "delete_event", "update_event",
        "kill_process", "terminate_process", "set_setting", "write_registry",
    ]
)


def _is_destructive(tool_name: str) -> bool:
    lower = tool_name.lower()
    return any(frag in lower for frag in _DESTRUCTIVE_TOOL_FRAGMENTS)


class CapabilityManifest:
    """Builds the plain-text capability manifest that the planner model reads.

    The manifest is regenerated by calling :meth:`refresh` and written to
    *manifest_path*. Call :meth:`load` to read the current file without
    rebuilding.
    """

    def __init__(self, manifest_path: Path) -> None:
        self._path = manifest_path

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def build(
        self,
        model_registry: ModelRegistry,
        mcp_manager: MCPManager,
        workflow_registry: WorkflowCapabilityRegistry,
        workflow_storage: WorkflowStorage,
    ) -> str:
        """Generate and return the manifest text (does NOT write to disk)."""
        sections: list[str] = []

        sections.append(self._section_models(model_registry, workflow_registry))
        sections.append(self._section_mcp_tools(mcp_manager))
        sections.append(self._section_anythink_capabilities())
        sections.append(self._section_stage_types())
        sections.append(self._section_saved_workflows(workflow_storage))

        return "\n".join(sections)

    def refresh(
        self,
        model_registry: ModelRegistry,
        mcp_manager: MCPManager,
        workflow_registry: WorkflowCapabilityRegistry,
        workflow_storage: WorkflowStorage,
    ) -> None:
        """Rebuild and write the manifest to disk."""
        text = self.build(model_registry, mcp_manager, workflow_registry, workflow_storage)
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._path.write_text(text, encoding="utf-8")

    def load(self) -> str:
        """Return the current manifest text from disk, or an empty string."""
        if not self._path.exists():
            return ""
        return self._path.read_text(encoding="utf-8")

    @property
    def path(self) -> Path:
        return self._path

    # ------------------------------------------------------------------
    # Section builders
    # ------------------------------------------------------------------

    def _section_models(
        self,
        model_registry: ModelRegistry,
        workflow_registry: WorkflowCapabilityRegistry,
    ) -> str:
        aliases = model_registry.list_all()
        local_lines: list[str] = []
        cloud_lines: list[str] = []

        for alias in aliases:
            tags = workflow_registry.get_tags(alias.alias)
            fallback_chain = workflow_registry.get_fallback_chain(alias.alias)
            entry_lines = [
                f"alias: {alias.alias}",
                f"  model: {alias.model_id}",
                f"  provider: {alias.provider}",
                f"  context_window: {alias.context_window}",
                f"  tags: {', '.join(tags) if tags else '(none)'}",
            ]
            if fallback_chain:
                entry_lines.append(f"  fallback: {', '.join(fallback_chain)}")
            entry_lines.append("")

            if alias.provider.lower() in _LOCAL_PROVIDERS:
                local_lines.extend(entry_lines)
            else:
                cloud_lines.extend(entry_lines)

        parts: list[str] = ["[LOCAL MODELS]"]
        parts.extend(local_lines if local_lines else ["(none)\n"])
        parts.append("[CLOUD MODELS]")
        parts.extend(cloud_lines if cloud_lines else ["(none)\n"])
        return "\n".join(parts)

    def _section_mcp_tools(self, mcp_manager: MCPManager) -> str:
        tools = mcp_manager.list_tools()
        # Group by server_name
        by_server: dict[str, list[Any]] = {}
        for tool in tools:
            by_server.setdefault(tool.server_name, []).append(tool)

        lines: list[str] = ["[MCP TOOLS]"]
        if not tools:
            lines.append("(none)\n")
            return "\n".join(lines)

        for server_name in sorted(by_server):
            server_tools = by_server[server_name]
            lines.append(f"server: {server_name}")
            for tool in server_tools:
                lines.append(f"  tool: {tool.name}")
                lines.append(f"    description: {tool.description}")
                # Extract params from input_schema
                params = self._extract_params(tool.input_schema)
                if params:
                    lines.append(f"    params: {params}")
                if _is_destructive(tool.name):
                    lines.append("    DESTRUCTIVE: requires user confirmation")
            lines.append("")

        return "\n".join(lines)

    def _extract_params(self, schema: dict[str, Any]) -> str:
        """Return a compact param list string from a JSON Schema dict."""
        props = schema.get("properties", {})
        if not props:
            return ""
        required = set(schema.get("required", []))
        parts: list[str] = []
        for name, spec in props.items():
            ptype = spec.get("type", "any")
            req = "" if name in required else "?"
            parts.append(f"{name} ({ptype}{req})")
        return ", ".join(parts)

    def _section_anythink_capabilities(self) -> str:
        return "\n".join(
            [
                "[ANYTHINK CAPABILITIES]",
                "rag_search: Query a loaded RAG index by natural language",
                "web_search: Search the web and return results (requires search toggle on)",
                "session_history: Read previous conversation sessions",
                "desktop_notification: Send a desktop notification",
                "clipboard_write: Write text to system clipboard",
                "screenshot: Capture the screen and use as context",
                "",
            ]
        )

    def _section_stage_types(self) -> str:
        descriptions = {
            StageType.PLANNER: "Reads intent and produces structured plan (always Stage 1)",
            StageType.MCP_CALL: "Executes one or more MCP tool calls — no LLM",
            StageType.LLM_SPECIALIST: "Sends context to a specific model for processing",
            StageType.USER_APPROVAL: "Pauses and waits for user confirmation to continue",
            StageType.CONDITION: "Routes to Branch A or B based on a condition expression",
            StageType.FORMATTER: "Converts stage output to a specific format",
            StageType.LOOP: "Repeats a sub-pipeline for each item in a collection",
        }
        lines = ["[STAGE TYPES]"]
        for stype, desc in descriptions.items():
            lines.append(f"{stype.value}: {desc}")
        lines.append("")
        return "\n".join(lines)

    def _section_saved_workflows(self, workflow_storage: WorkflowStorage) -> str:
        summaries = workflow_storage.list_summaries()
        lines = ["[SAVED WORKFLOWS]"]
        if not summaries:
            lines.append("(none)\n")
        else:
            for s in summaries:
                lines.append(f"name: {s['name']}")
                lines.append(f"  description: {s.get('trigger', '')}")
                lines.append(f"  stage_count: {s.get('stage_count', 0)}")
                lines.append("")
        return "\n".join(lines)
